/* Bingo IMARA · Centro de Finanzas 2026
   Módulo aislado: no modifica login ni arranque base. */
(function(){
'use strict';
if(location.hash.startsWith('#public')||location.hash.startsWith('#mobile='))return;
const API='https://fpevaukkbtruplwptufu.supabase.co/functions/v1/bingo-finance';
const SESSION_KEY='imaraPrivateSessionV1';
let role='',rows=[],metrics={},history=[],poll=null,currentSale=null;
const money=n=>new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(Number(n)||0);
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const statusName=s=>({pending:'Pendiente',approved:'Pagado',rejected:'Rechazado',refunded:'Devuelto'}[s]||s||'—');
const statusClass=s=>({pending:'warn',approved:'good',rejected:'bad',refunded:'refund'}[s]||'');

async function api(action,payload={}){
 const token=sessionStorage.getItem(SESSION_KEY)||'';if(!token)throw new Error('Sesión no disponible. Vuelve a iniciar sesión.');
 const ctl=new AbortController(),tm=setTimeout(()=>ctl.abort(),12000);
 try{const r=await fetch(API,{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+token},cache:'no-store',signal:ctl.signal,body:JSON.stringify({action,...payload})});let d={};try{d=await r.json()}catch(e){}if(!r.ok)throw new Error(d.error||'No fue posible completar la operación.');return d;}finally{clearTimeout(tm);}
}
function installCss(){if(document.getElementById('imaraFinanceCss'))return;const s=document.createElement('style');s.id='imaraFinanceCss';s.textContent=`
 .imara-role.finance{background:#263e52;color:#aee7ff}.finance-view{display:grid;gap:16px}.finance-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.finance-kpi{padding:16px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(160deg,#111b30,#17233a)}.finance-kpi span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.8px}.finance-kpi strong{display:block;margin-top:7px;font-size:27px}.finance-toolbar{display:flex;gap:9px;flex-wrap:wrap;align-items:center}.finance-toolbar .input{min-width:170px}.finance-table{overflow:auto;border:1px solid var(--line);border-radius:16px}.finance-table table{min-width:1180px}.finance-status{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:900}.finance-status.good{background:rgba(43,212,167,.13);color:#85f4d5}.finance-status.warn{background:rgba(255,191,71,.13);color:#ffd37e}.finance-status.bad{background:rgba(255,102,119,.13);color:#ffa1ac}.finance-status.refund{background:rgba(110,174,255,.13);color:#abd1ff}.finance-actions{display:flex;gap:5px;flex-wrap:wrap}.finance-history{display:grid;gap:7px;max-height:360px;overflow:auto}.finance-event{padding:10px 11px;border:1px solid var(--line);border-radius:13px;background:#10182a}.finance-event small{color:var(--muted)}.finance-create{padding:14px;border:1px solid rgba(141,107,255,.25);border-radius:16px;background:rgba(141,107,255,.07)}
 body.imara-finance #imaraOps{display:none!important}body.imara-finance .nav button:not([data-view="finance"]){display:none!important}body.imara-finance #backupBtn,body.imara-finance #openPublicBtn{display:none!important}
 @media(max-width:900px){.finance-kpis{grid-template-columns:1fr 1fr}}@media(max-width:560px){.finance-kpis{grid-template-columns:1fr}.finance-toolbar .input{width:100%}}
 `;document.head.appendChild(s);}
function ensureView(){
 const nav=document.querySelector('.nav');if(!nav)return false;
 let btn=document.querySelector('.nav [data-view="finance"]');if(!btn){btn=document.createElement('button');btn.dataset.view='finance';btn.textContent='💰 Finanzas';nav.appendChild(btn);btn.addEventListener('click',showFinance);}
 let view=document.getElementById('view-finance');if(!view){view=document.createElement('section');view.id='view-finance';view.className='view hidden';document.querySelector('main.content')?.appendChild(view);}
 return true;
}
function showFinance(){document.querySelectorAll('.view').forEach(x=>x.classList.add('hidden'));document.getElementById('view-finance')?.classList.remove('hidden');document.querySelectorAll('.nav button').forEach(b=>b.classList.toggle('active',b.dataset.view==='finance'));const t=document.getElementById('pageTitle'),s=document.getElementById('pageSubtitle');if(t)t.textContent='Finanzas';if(s)s.textContent='Recaudo, pagos, devoluciones y trazabilidad financiera.';render();}
function detectRole(){const chip=document.querySelector('#imaraUserChip .imara-role');if(!chip)return '';if(chip.classList.contains('admin'))return 'admin';if(chip.classList.contains('finance'))return 'finance';if(chip.classList.contains('member'))return 'member';return '';}
function applyRole(){const r=detectRole();if(!r||r===role)return;role=r;document.body.classList.toggle('imara-finance',role==='finance');const chip=document.querySelector('#imaraUserChip .imara-role.finance');if(chip)chip.textContent='FINANZAS';if(['admin','finance'].includes(role)){ensureView();refreshAll();if(!poll)poll=setInterval(()=>{if(!document.hidden)refreshAll(false);},20000);if(role==='finance')setTimeout(showFinance,0);}else{document.querySelector('.nav [data-view="finance"]')?.remove();document.getElementById('view-finance')?.remove();}}
function renderShell(){const v=document.getElementById('view-finance');if(!v)return; if(v.dataset.ready)return;v.dataset.ready='1';v.innerHTML=`<div class="finance-view">
 <div class="card"><div class="section-title"><div><h3>💰 Centro Financiero</h3><div class="muted">El pago confirmado habilita automáticamente el cartón para jugar. Las devoluciones salen del recaudo.</div></div><button class="btn" id="financeRefresh">↻ Actualizar</button></div><div class="finance-kpis" id="financeKpis"></div></div>
 <div class="card"><div class="section-title"><h3>Movimientos y correcciones</h3><span class="muted" id="financeCount"></span></div><div class="finance-toolbar"><input class="input" id="financeSearch" placeholder="Buscar cartón, nombre, celular o vendedor"><select class="input" id="financeFilter"><option value="">Todos los estados</option><option value="pending">Pendientes</option><option value="approved">Pagados</option><option value="refunded">Devueltos</option><option value="rejected">Rechazados</option></select></div><div id="financeRows" style="margin-top:12px"></div></div>
 <div class="grid two"><div class="card"><div class="section-title"><h3>🧾 Historial financiero</h3><span class="muted">Últimos cambios</span></div><div class="finance-history" id="financeHistory"></div></div><div class="card" id="financeAdminBox"></div></div>
 </div>`;
 v.querySelector('#financeRefresh').onclick=()=>refreshAll(true);v.querySelector('#financeSearch').addEventListener('input',renderRows);v.querySelector('#financeFilter').addEventListener('change',renderRows);
 const d=document.createElement('dialog');d.id='financeEditDialog';d.innerHTML=`<div class="modal-head"><strong id="financeEditTitle">Corregir pago</strong><button class="mini" id="financeClose">✕</button></div><div class="modal-body"><div class="form-grid"><label>Comprador / alias<input class="input" id="finAlias"></label><label>Medio de pago<input class="input" id="finMethod"></label><label>Valor<input class="input" id="finAmount" type="number" min="0"></label><label>Estado<select class="input" id="finStatus"><option value="pending">Pendiente</option><option value="approved">Pagado</option><option value="refunded">Devuelto</option><option value="rejected">Rechazado</option></select></label><label class="full">Motivo / nota financiera<textarea class="input" id="finNote" placeholder="Obligatorio para devolución, rechazo o regreso a pendiente"></textarea></label><div class="full notice" id="finPhone"></div></div></div><div class="modal-foot"><button class="btn" id="finCancel">Cancelar</button><button class="btn good" id="finSave">Guardar corrección</button></div>`;document.body.appendChild(d);d.querySelector('#financeClose').onclick=()=>d.close();d.querySelector('#finCancel').onclick=()=>d.close();d.querySelector('#finSave').onclick=saveEdit;
}
function renderKpis(){const h=document.getElementById('financeKpis');if(!h)return;h.innerHTML=`<div class="finance-kpi"><span>Recaudo neto</span><strong>${money(metrics.netRevenue)}</strong><small class="muted">${metrics.approvedCount||0} pagos vigentes</small></div><div class="finance-kpi"><span>Pendiente</span><strong>${money(metrics.pendingAmount)}</strong><small class="muted">${metrics.pendingCount||0} por confirmar</small></div><div class="finance-kpi"><span>Devuelto</span><strong>${money(metrics.refundedAmount)}</strong><small class="muted">${metrics.refundedCount||0} devoluciones</small></div><div class="finance-kpi"><span>Ventas registradas</span><strong>${metrics.totalSales||0}</strong><small class="muted">Todos los estados</small></div>`;}
function filtered(){const q=(document.getElementById('financeSearch')?.value||'').trim().toLowerCase(),f=document.getElementById('financeFilter')?.value||'';return rows.filter(r=>(!f||r.payment_status===f)&&(!q||[r.card_id,r.buyer_alias,r.buyer_phone,r.seller_name,r.payment_method].join(' ').toLowerCase().includes(q)));}
function renderRows(){const host=document.getElementById('financeRows');if(!host)return;const list=filtered();document.getElementById('financeCount').textContent=`${list.length} de ${rows.length}`;host.innerHTML=list.length?`<div class="finance-table"><table><thead><tr><th>Cartón</th><th>Comprador</th><th>Celular</th><th>Vendedor</th><th>Medio</th><th>Valor</th><th>Estado</th><th>Fechas</th><th>Acciones</th></tr></thead><tbody>${list.map(r=>`<tr><td><strong>${esc(r.card_id)}</strong><br><small class="muted">${esc(r.card_status||'')}</small></td><td>${esc(r.buyer_alias||'—')}</td><td>${esc(r.buyer_phone||'—')}</td><td>${esc(r.seller_name||'—')}</td><td>${esc(r.payment_method||'—')}</td><td><strong>${money(r.amount)}</strong></td><td><span class="finance-status ${statusClass(r.payment_status)}">${statusName(r.payment_status)}</span>${r.finance_note?`<br><small class="muted">${esc(r.finance_note)}</small>`:''}</td><td><small>Registro: ${fmt(r.submitted_at)}${r.approved_at?`<br>Pago: ${fmt(r.approved_at)}`:''}${r.refunded_at?`<br>Dev.: ${fmt(r.refunded_at)}`:''}</small></td><td><div class="finance-actions"><button class="mini" data-paid="${r.id}">✅ Pagado</button><button class="mini" data-edit="${r.id}">✏️ Corregir</button><button class="mini" data-refund="${r.id}">↩ Devuelto</button><button class="mini" data-copy="${r.id}">📋 Copiar</button></div></td></tr>`).join('')}</tbody></table></div>`:'<div class="muted" style="padding:16px">No hay movimientos con esos filtros.</div>';
 host.querySelectorAll('[data-paid]').forEach(b=>b.onclick=()=>quickStatus(b.dataset.paid,'approved'));
 host.querySelectorAll('[data-refund]').forEach(b=>b.onclick=()=>quickStatus(b.dataset.refund,'refunded'));
 host.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>openEdit(b.dataset.edit));
 host.querySelectorAll('[data-copy]').forEach(b=>b.onclick=()=>copyDetail(b.dataset.copy));
}
function renderHistory(){const h=document.getElementById('financeHistory');if(!h)return;h.innerHTML=history.length?history.slice(0,120).map(e=>`<div class="finance-event"><strong>${esc(e.card_id)} · ${statusName(e.to_status)}</strong><br><small>${fmt(e.created_at)} · ${esc(e.actor_name||'Sistema')} · ${money(e.amount)}</small>${e.note?`<div style="margin-top:4px">${esc(e.note)}</div>`:''}</div>`).join(''):'<div class="muted">Aún no hay correcciones financieras registradas.</div>';}
function renderAdminBox(){const h=document.getElementById('financeAdminBox');if(!h)return;if(role!=='admin'){h.innerHTML=`<div class="section-title"><h3>🔐 Permisos de Finanzas</h3></div><div class="success">Puedes revisar todas las ventas, confirmar pagos, corregir estados y registrar devoluciones. No tienes acceso a juego, rondas ni administración de usuarios.</div>`;return;}h.innerHTML=`<div class="section-title"><h3>👤 Crear acceso Finanzas</h3></div><div class="finance-create"><div class="form-grid"><label>Usuario<input class="input" id="finNewUser"></label><label>Nombre visible<input class="input" id="finNewName"></label><label class="full">Contraseña temporal<input class="input" id="finNewPass" type="password" minlength="8"></label></div><button class="btn primary" id="finCreateUser" style="margin-top:10px">Crear usuario Finanzas</button><div class="footer-note">Sin correo. La persona entra con Usuario + Contraseña y solo verá Finanzas.</div></div>`;h.querySelector('#finCreateUser').onclick=createFinanceUser;}
function render(){renderShell();renderKpis();renderRows();renderHistory();renderAdminBox();}
function fmt(v){if(!v)return '—';try{return new Date(v).toLocaleString('es-CO');}catch(e){return String(v);}}
async function refreshAll(showError=false){if(!['admin','finance'].includes(role))return;try{const [a,b]=await Promise.all([api('finance-list'),api('finance-history')]);rows=a.sales||[];metrics=a.metrics||{};history=b.events||[];render();}catch(e){if(showError)alert(e.message);}}
async function quickStatus(id,target){const r=rows.find(x=>x.id===id);if(!r)return;if(r.payment_status===target){alert(`Este pago ya está como ${statusName(target)}.`);return;}let note='';if(target==='refunded')note=prompt(`Motivo de devolución de ${r.card_id}:`,'')||'';if(target==='refunded'&&!note.trim())return;try{await api('finance-update',{sale_id:id,payment_status:target,note});if(typeof toast==='function')toast(target==='approved'?`✅ ${r.card_id} quedó Pagado`:`↩ ${r.card_id} quedó Devuelto`);await refreshAll();}catch(e){alert(e.message);}}
function openEdit(id){currentSale=rows.find(x=>x.id===id);if(!currentSale)return;document.getElementById('financeEditTitle').textContent=`Corregir ${currentSale.card_id}`;document.getElementById('finAlias').value=currentSale.buyer_alias||'';document.getElementById('finMethod').value=currentSale.payment_method||'';document.getElementById('finAmount').value=currentSale.amount||0;document.getElementById('finStatus').value=currentSale.payment_status;document.getElementById('finNote').value='';document.getElementById('finPhone').innerHTML=`📱 Celular protegido: <strong>${esc(currentSale.buyer_phone||'—')}</strong><br><small>El número se descifra solo para usuarios autorizados y no se guarda en localStorage.</small>`;document.getElementById('financeEditDialog').showModal();}
async function saveEdit(){if(!currentSale)return;const target=document.getElementById('finStatus').value,note=document.getElementById('finNote').value.trim();if(['pending','rejected','refunded'].includes(target)&&target!==currentSale.payment_status&&!note){alert('Escribe el motivo de la corrección.');return;}const btn=document.getElementById('finSave'),old=btn.textContent;btn.disabled=true;btn.textContent='Guardando…';try{await api('finance-update',{sale_id:currentSale.id,payment_status:target,buyer_alias:document.getElementById('finAlias').value,payment_method:document.getElementById('finMethod').value,amount:Number(document.getElementById('finAmount').value)||0,note});document.getElementById('financeEditDialog').close();if(typeof toast==='function')toast(`💰 ${currentSale.card_id} actualizado`);currentSale=null;await refreshAll();}catch(e){alert(e.message);}finally{btn.disabled=false;btn.textContent=old;}}
async function copyDetail(id){const r=rows.find(x=>x.id===id);if(!r)return;const text=[`Bingo IMARA · Detalle de pago`,`Cartón: ${r.card_id}`,`Participante: ${r.buyer_alias||'—'}`,`Celular: ${r.buyer_phone||'—'}`,`Vendedor: ${r.seller_name||'—'}`,`Medio: ${r.payment_method||'—'}`,`Valor: ${money(r.amount)}`,`Estado: ${statusName(r.payment_status)}`,`Registro: ${fmt(r.submitted_at)}`,r.approved_at?`Confirmado: ${fmt(r.approved_at)}`:'',r.refunded_at?`Devuelto: ${fmt(r.refunded_at)}`:'',r.finance_note?`Nota: ${r.finance_note}`:''].filter(Boolean).join('\n');try{await navigator.clipboard.writeText(text);if(typeof toast==='function')toast('📋 Detalle financiero copiado');}catch(e){prompt('Copia el detalle:',text);}}
async function createFinanceUser(){const u=document.getElementById('finNewUser').value.trim(),n=document.getElementById('finNewName').value.trim(),p=document.getElementById('finNewPass').value;if(!u||p.length<8){alert('Usuario y contraseña de mínimo 8 caracteres.');return;}const b=document.getElementById('finCreateUser'),old=b.textContent;b.disabled=true;b.textContent='Creando…';try{await api('create-finance-user',{username:u,display_name:n||u,password:p});document.getElementById('finNewUser').value='';document.getElementById('finNewName').value='';document.getElementById('finNewPass').value='';alert(`✅ Usuario @${u} creado con rol Finanzas.`);}catch(e){alert(e.message);}finally{b.disabled=false;b.textContent=old;}}
installCss();
const observer=new MutationObserver(()=>{applyRole();if(['admin','finance'].includes(role))ensureView();});observer.observe(document.body,{childList:true,subtree:true});
setInterval(applyRole,800);applyRole();
})();
