/* BINGO IMARA · Show público + métricas de juego */
(function(){
  let lastPublicWinnerKey='',lastDrawCount=-1,audioCtx=null,soundEnabled=localStorage.getItem('imaraPublicSound')==='on';
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));

  function installStyles(){if(document.getElementById('imaraPublicFxStyles'))return;const s=document.createElement('style');s.id='imaraPublicFxStyles';s.textContent=`
    .event-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:14px 0}.event-stat{padding:12px;border-radius:16px;background:rgba(9,14,25,.46);border:1px solid var(--line);text-align:center;overflow:hidden}.event-stat span{display:block;font-size:9px;letter-spacing:.9px;text-transform:uppercase;color:var(--muted);font-weight:900}.event-stat strong{display:block;font-size:24px;margin-top:4px}.event-stat.near strong{color:#ffd278}.event-stat.won strong{color:#8df3d6}.event-stat.money strong{font-size:17px;color:#cabdff}.public .event-stats{grid-template-columns:repeat(3,minmax(0,1fr));margin:14px 0}.public .event-stat{background:rgba(255,255,255,.055)}.public .event-stat strong{font-size:27px}.winner-position-list{display:flex;gap:7px;flex-wrap:wrap;margin-top:10px}.winner-position-chip{padding:7px 10px;border-radius:999px;background:rgba(141,107,255,.13);border:1px solid rgba(141,107,255,.28);font-size:11px;font-weight:800}.public-winner-name{display:inline-block;transform-origin:center;animation:winnerNameOpen .8s cubic-bezier(.16,1,.3,1) both}.public-winner-extra{display:block;font-size:13px;margin-top:6px;color:#ffe0eb;animation:winnerSubIn .5s .35s both}.public-sound-btn{position:fixed;right:16px;top:16px;z-index:99990;border:1px solid rgba(255,255,255,.18);background:rgba(13,19,32,.8);color:#fff;border-radius:999px;padding:8px 12px;font-weight:800;backdrop-filter:blur(8px)}body.public-only .brand-logo,body.public-only .public-logo,body.public-only .logo-preview{filter:drop-shadow(0 0 18px rgba(255,91,143,.32));animation:logoShowPulse 3s ease-in-out infinite!important}body.roulette-active .dual-ball-stage .bingo-letter-ball{animation:letterMix .34s ease-in-out infinite alternate!important}body.roulette-active .dual-ball-stage .bingo-number-ball{animation:numberMix .34s ease-in-out infinite alternate!important}.public-confetti{position:fixed;top:-20px;z-index:999998;pointer-events:none;width:11px;height:18px;border-radius:3px;animation:publicConfettiFall var(--d) linear forwards}.public-winner-burst{position:fixed;inset:0;pointer-events:none;z-index:999997;background:radial-gradient(circle at center,rgba(255,255,255,.16),transparent 45%);animation:burstFlash .7s ease-out forwards}
    @keyframes winnerNameOpen{0%{opacity:0;transform:scaleX(0) scaleY(.75);letter-spacing:-18px;filter:blur(8px)}65%{opacity:1;transform:scaleX(1.06) scaleY(1.04);letter-spacing:4px;filter:blur(0)}100%{transform:none;letter-spacing:1px}}
    @keyframes winnerSubIn{from{opacity:0;transform:translateY(10px)}to{opacity:1;transform:none}}@keyframes logoShowPulse{0%,100%{transform:translateY(0) scale(1)}50%{transform:translateY(-5px) scale(1.035)}}@keyframes letterMix{from{transform:translateX(-10px) translateY(5px) rotate(-11deg) scale(.95)}to{transform:translateX(12px) translateY(-7px) rotate(12deg) scale(1.05)}}@keyframes numberMix{from{transform:translateX(11px) translateY(-6px) rotate(10deg) scale(1.04)}to{transform:translateX(-12px) translateY(7px) rotate(-11deg) scale(.96)}}@keyframes publicConfettiFall{to{transform:translate3d(var(--x),110vh,0) rotate(820deg);opacity:.92}}@keyframes burstFlash{0%{opacity:0}25%{opacity:1}100%{opacity:0}}
    @media(max-width:760px){.event-stats{grid-template-columns:repeat(2,1fr)}.public .event-stats{grid-template-columns:repeat(3,1fr)}.event-stat strong,.public .event-stat strong{font-size:19px}.event-stat.money strong{font-size:13px}.public-sound-btn{top:auto;bottom:12px}}
  `;document.head.appendChild(s);}

  function groupsFor(pattern){const rows=[0,1,2,3,4].map(r=>[0,1,2,3,4].map(c=>[r,c])),cols=[0,1,2,3,4].map(c=>[0,1,2,3,4].map(r=>[r,c])),d1=[0,1,2,3,4].map(i=>[i,i]),d2=[0,1,2,3,4].map(i=>[i,4-i]);const uniq=a=>[...new Map(a.map(x=>[x.join(','),x])).values()];if(pattern==='row')return rows;if(pattern==='column')return cols;if(pattern==='col_b')return [cols[0]];if(pattern==='col_i')return [cols[1]];if(pattern==='col_n')return [cols[2]];if(pattern==='col_g')return [cols[3]];if(pattern==='col_o')return [cols[4]];if(pattern==='diagonal')return [d1,d2];if(pattern==='corners')return [[[0,0],[0,4],[4,0],[4,4]]];if(pattern==='x')return [uniq([...d1,...d2])];if(pattern==='plus')return [uniq([...rows[2],...cols[2]])];if(pattern==='t')return [uniq([...rows[0],...cols[2]])];if(pattern==='h')return [uniq([...cols[0],...cols[4],...rows[2]])];if(pattern==='u')return [uniq([...cols[0],...cols[4],...rows[4]])];if(pattern==='l_left')return [uniq([...cols[0],...rows[4]])];if(pattern==='l_right')return [uniq([...cols[4],...rows[4]])];if(pattern==='frame')return [uniq([...rows[0],...rows[4],...cols[0],...cols[4]])];if(pattern==='full')return [[...rows.flat()]];return [...rows,...cols,d1,d2];}
  function missingFor(card){const groups=groupsFor(state.round.pattern);let best=99;for(const g of groups){let missing=0;for(const [r,c] of g){const v=card.grid?.[r]?.[c];if(v!=='FREE'&&!state.drawn.includes(Number(v)))missing++;}best=Math.min(best,missing);}return best;}
  function localPaidCards(){return (state.cards||[]).filter(c=>['Pagado','Ganador'].includes(c.status));}
  function eventMetrics(){const cloud=window.IMARA_CLOUD_METRICS;const paid=cloud?.cloudCards?.length?cloud.cloudCards.filter(c=>c.payment_status==='approved'||['Pagado','Ganador'].includes(c.status)).map(c=>({id:c.id,buyer:c.buyer,status:c.status,grid:c.grid})):localPaidCards();const people=new Set(paid.map(c=>(c.buyer||c.id).trim().toLowerCase()).filter(Boolean));const near=paid.filter(c=>c.status!=='Ganador'&&missingFor(c)===1).length;const winners=(cloud?.winners?.length?cloud.winners:state.winners||[]);return {participants:cloud?.activeParticipants??people.size,paid:cloud?.paidCards??paid.length,near,winners:winners.length,revenue:cloud?.revenue??(paid.length*(Number(state.settings.price)||0)),winnerList:winners};}

  function statsHtml(publicMode=false){const m=eventMetrics();return `<div class="event-stats"><div class="event-stat"><span>Participantes jugando</span><strong>${m.participants}</strong></div><div class="event-stat near"><span>A 1 balota de ganar</span><strong>${m.near}</strong></div><div class="event-stat won"><span>Puestos entregados</span><strong>${m.winners}</strong></div>${publicMode?'':`<div class="event-stat money"><span>Recaudo aprobado</span><strong>${new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(m.revenue)}</strong></div>`}</div>`;}
  function renderAdminStats(){const game=document.getElementById('view-game');if(!game)return;let box=document.getElementById('adminEventStats');if(!box){box=document.createElement('div');box.id='adminEventStats';box.className='card';box.style.margin='16px 0';const auto=document.getElementById('autoWinnerStatus')?.closest('.card');if(auto)auto.insertAdjacentElement('afterend',box);else game.appendChild(box);}const m=eventMetrics();box.innerHTML=`<div class="section-title"><h3>📊 Estado en vivo de la partida</h3><span class="muted">Se actualiza con ventas y balotas</span></div>${statsHtml(false)}${m.winnerList.length?`<div class="winner-position-list">${m.winnerList.slice(0,6).map((w,i)=>`<span class="winner-position-chip">${i+1}º · ${esc(w.card_id||w.cardId||'')} ${esc(w.buyer||'')}</span>`).join('')}</div>`:''}`;}
  function renderPublicStats(){const main=document.querySelector('#view-public .public-main');if(!main)return;let box=document.getElementById('publicEventStats');if(!box){box=document.createElement('div');box.id='publicEventStats';const board=document.getElementById('publicBoard');main.insertBefore(box,board);}box.innerHTML=statsHtml(true);}

  function soundButton(){if(!document.body.classList.contains('public-only'))return;let b=document.getElementById('publicSoundBtn');if(b)return;b=document.createElement('button');b.id='publicSoundBtn';b.className='public-sound-btn';b.textContent=soundEnabled?'🔊 Sonido ON':'🔇 Activar sonido';b.onclick=()=>{soundEnabled=!soundEnabled;localStorage.setItem('imaraPublicSound',soundEnabled?'on':'off');if(soundEnabled)ensureAudio();b.textContent=soundEnabled?'🔊 Sonido ON':'🔇 Activar sonido';};document.body.appendChild(b);}
  function ensureAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();return audioCtx;}
  function tone(freq=520,dur=.12,type='sine',vol=.05,delay=0){if(!soundEnabled||!document.body.classList.contains('public-only'))return;try{const ctx=ensureAudio(),o=ctx.createOscillator(),g=ctx.createGain(),t=ctx.currentTime+delay;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(.001,t);g.gain.exponentialRampToValueAtTime(vol,t+.015);g.gain.exponentialRampToValueAtTime(.001,t+dur);o.connect(g).connect(ctx.destination);o.start(t);o.stop(t+dur+.02);}catch(e){}}
  function ballSound(){tone(420,.09,'triangle',.035);tone(620,.12,'sine',.045,.08);tone(880,.16,'sine',.03,.18);}
  function winnerSound(){[523,659,784,1046].forEach((f,i)=>tone(f,.28,'triangle',.055,i*.12));}
  function publicConfetti(){if(!document.body.classList.contains('public-only'))return;const colors=['#ff5b8f','#8d6bff','#2bd4a7','#ffbf47','#fff'];const burst=document.createElement('div');burst.className='public-winner-burst';document.body.appendChild(burst);setTimeout(()=>burst.remove(),800);for(let i=0;i<150;i++){const x=document.createElement('i');x.className='public-confetti';x.style.left=Math.random()*100+'vw';x.style.background=colors[i%colors.length];x.style.setProperty('--d',(2.3+Math.random()*2.5)+'s');x.style.setProperty('--x',((Math.random()-.5)*360)+'px');x.style.animationDelay=(Math.random()*.7)+'s';document.body.appendChild(x);setTimeout(()=>x.remove(),5600);}}
  function decorateWinner(){const banner=document.querySelector('#publicWinner .winner-banner');if(!banner)return;const latest=(window.IMARA_CLOUD_METRICS?.winners?.[0])||(state.winners?.[0]);if(!latest)return;const id=latest.card_id||latest.cardId||'',buyer=latest.buyer||'';const key=[id,buyer,latest.created_at||latest.at||''].join('|');banner.innerHTML=`🏆 <span class="public-winner-name">¡TENEMOS GANADOR! · ${esc(id)}${buyer?' · '+esc(buyer):''}</span><span class="public-winner-extra">Puesto ${eventMetrics().winners} confirmado por Bingo IMARA</span>`;if(document.body.classList.contains('public-only')&&key!==lastPublicWinnerKey){lastPublicWinnerKey=key;publicConfetti();winnerSound();}}

  function afterRender(){renderAdminStats();renderPublicStats();soundButton();decorateWinner();if(document.body.classList.contains('public-only')){const count=(state.drawn||[]).length;if(lastDrawCount>=0&&count>lastDrawCount)ballSound();lastDrawCount=count;}}
  if(typeof renderAll==='function'){const base=renderAll;renderAll=function(){const r=base();setTimeout(afterRender,0);return r;};}
  window.addEventListener('imara-cloud-updated',()=>setTimeout(afterRender,0));
  installStyles();setTimeout(afterRender,80);
})();